In [ ]:
!pip install dgl-cu111 -f https://data.dgl.ai/wheels/repo.html

Looking in links: https://data.dgl.ai/wheels/repo.html
     |████████████████████████████████| 165.0 MB 50 kB/s 


In [ ]:
!pip install dgl -f https://data.dgl.ai/wheels/repo.html

Looking in links: https://data.dgl.ai/wheels/repo.html
     |████████████████████████████████| 5.7 MB 274 kB/s 


In [5]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [1]:
import dgl
import numpy as np
import networkx as nx
import os
import pickle

In [ ]:
!gdown --id 139k8AKUj1HDJ3QrJ_EnwMh7wv4qaQiqT

Downloading...
From: https://drive.google.com/uc?id=139k8AKUj1HDJ3QrJ_EnwMh7wv4qaQiqT
To: /content/pheme_dgl_full_roberta.pkl
100% 394M/394M [00:02<00:00, 137MB/s] 


In [2]:
data_dir = ""
filepath = os.path.join(data_dir,"pheme_dgl_full_roberta.pkl")
with open(filepath,"rb") as f:
    dataset = pickle.load(f)
#dataset - dgl graph which can be directly passed to a DGL model

In [8]:
#First Tree/Graph: Features, Labels, Masks
dataset[10].ndata['x'].shape

torch.Size([22, 1024])

In [ ]:
dataset[0].ndata['val_mask']

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# print(dataset[0].ndata['del_t'])
print(dataset[0].ndata['y'])
print(dataset[0].ndata['test_mask'])
print(dataset[0].ndata['val_mask'])
print(dataset[0].ndata['train_mask'])
print(dataset[0].ndata['x'].shape)
# print(len(dataset[0].ndata['train_mask']))

tensor([ 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([14, 1024])


In [12]:
lens = [len(dataset[i].ndata['train_mask']) for i in range(len(dataset))]

In [14]:
print(lens)

[14, 1, 18, 2, 6, 30, 9, 1, 13, 15, 22, 23, 11, 15, 31, 4, 19, 21, 1, 10, 5, 1, 1, 22, 12, 10, 20, 1, 109, 1, 2, 4, 20, 1, 1, 1, 10, 19, 3, 16, 22, 12, 1, 8, 5, 3, 2, 10, 14, 16, 7, 2, 1, 5, 36, 2, 1, 17, 27, 15, 38, 9, 54, 5, 48, 11, 4, 14, 11, 4, 17, 14, 19, 18, 2, 7, 5, 17, 10, 18, 10, 1, 3, 5, 7, 7, 50, 3, 68, 9, 4, 9, 10, 8, 23, 15, 5, 14, 18, 1, 1, 13, 7, 4, 16, 19, 3, 9, 1, 22, 16, 9, 5, 92, 1, 13, 20, 9, 6, 17, 29, 11, 19, 8, 12, 2, 19, 32, 4, 18, 16, 20, 1, 79, 60, 20, 11, 1, 19, 1, 28, 1, 22, 7, 18, 5, 1, 14, 4, 18, 7, 5, 21, 13, 8, 2, 14, 89, 30, 17, 16, 4, 18, 69, 20, 10, 3, 20, 11, 10, 25, 10, 1, 24, 12, 3, 1, 23, 24, 15, 2, 1, 4, 24, 8, 3, 11, 2, 14, 14, 5, 1, 21, 20, 8, 5, 1, 3, 15, 1, 4, 1, 6, 6, 9, 28, 2, 2, 29, 19, 7, 8, 4, 7, 1, 13, 6, 3, 8, 6, 33, 6, 11, 3, 1, 20, 14, 7, 20, 57, 1, 30, 11, 8, 14, 20, 8, 27, 37, 2, 19, 18, 10, 4, 33, 1, 1, 8, 20, 67, 8, 1, 8, 25, 6, 37, 13, 7, 6, 18, 24, 1, 15, 3, 20, 1, 88, 2, 5, 1, 5, 49, 13, 15, 9, 18, 1, 11, 37, 2, 3, 17, 7, 12, 

In [11]:
gg = gg.tolist()
print(gg)
if 1 in gg:
    # get the position of 1 in gg
    print(gg.index(1))

[1]
0


In [11]:
dataset[0].adj(scipy_fmt='csr').toarray().shape #csr scipy sparse adj matrix structure

(14, 14)

In [ ]:
g = nx.DiGraph() #IGNORE

In [ ]:
g.add_edge(0,1) #IGNORE

In [ ]:
#IGNORE
for node in g:
    g.nodes[node]['x'] = np.zeros((768,))
    g.nodes[node]['y'] = 0

In [ ]:
#IGNORE
g_dgl = dgl.from_networkx(g,node_attrs=['x', 'y'])

In [ ]:
#IGNORE
g_dgl.ndata['x']

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
#testing finsler riemmanain
!git clone https://github.com/fedelopez77/sympa.git

Cloning into 'sympa'...
remote: Enumerating objects: 1069, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 1069 (delta 207), reused 199 (delta 148), pack-reused 794
Receiving objects: 100% (1069/1069), 6.79 MiB | 11.75 MiB/s, done.
Resolving deltas: 100% (717/717), done.


In [ ]:
!pip install git+https://github.com/geoopt/geoopt.git


  Cloning https://github.com/geoopt/geoopt.git to /tmp/pip-req-build-5gvdtkcc
  Running command git clone -q https://github.com/geoopt/geoopt.git /tmp/pip-req-build-5gvdtkcc
  Created wheel for geoopt: filename=geoopt-0.4.0-py3-none-any.whl size=85469 sha256=4431388f4b7cda9e92836fdab49ef9e83b11742e62c15fb3c68da771535c960d
  Stored in directory: /tmp/pip-ephem-wheel-cache-d112c0gt/wheels/e9/b9/1f/4238e702b8889c5329cc24bb3c1d020ab33de17df8ee1e8da4
Successfully built geoopt


In [ ]:
!pip install networkit

     |████████████████████████████████| 3.3 MB 4.6 MB/s 
  Created wheel for networkit: filename=networkit-9.1.1-cp37-cp37m-linux_x86_64.whl size=8407870 sha256=9d182479d36709b78cf15839f253981d8a6224d77fd6ec69b15faec2f4e9ae98
  Stored in directory: /root/.cache/pip/wheels/1d/8a/73/6e4a25c5aa05674de4c0b30190282728e11ad20853157e016b
Successfully built networkit


In [ ]:
!pip install tensorboardX

     |████████████████████████████████| 124 kB 4.2 MB/s 


In [ ]:
%cd sympa/

/content/sympa


In [ ]:
!python preprocess.py --graph=social-karate --run_id=1 


02/12/2022 17:27:14 Building graph: social-karate
02/12/2022 17:27:14 Graph named 'social-karate' with 34 nodes and 78 edges
02/12/2022 17:27:14 Building triplets for 34 nodes
02/12/2022 17:27:14 Total triplets: 561
02/12/2022 17:27:14 Saving to data/1/preprocessed-data.pt


In [ ]:
!python -m torch.distributed.launch train.py --n_procs=1 --data=1 --run_id=2 --results_file=out/results.csv

/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
02/12/2022 17:27:20 Namespace(batch_size=1000, burnin=10, data='1', debug=False, dims=3, epochs=100, grad_accum_steps=1, job_id=-1, learning_rate=0.01, load_model='', local_rank=0, manifold='euclidean', max_grad_norm=50.0, metric='wsum', n_procs=1, optim='rsgd', patience=50, reduce_factor=5, results_file='out/results.csv', run_id='2', save_epochs=10001, scale_coef=1, scale_init=1, scale_triplets=False, seed=42, subsample=-1, train_scale=False, val_every=5, weight_decay=0.0)
02/12/2022 17:27:20 Job ID: -1
02/12/2022 17:27:20 